#!/bin/bash

# TODO: parse pacman.conf for CacheDir property
cache_dir=/var/cache/pacman/pkg

xargs expac -S "$cache_dir/%f" | \
    grep -f <(find "$cache_dir" -type f -name '*.pkg.tar.xz' -maxdepth 1) | \
    xargs -L1 sh -c 'ipfs add --pin=false --progress=false "$0" || exit 255'
# TODO: enable configurable pinning? needs to manage state perhaps..
